### ISSUE TITLE
Get live changes

### ISSUE THREAD

**Issue by paviro** [johankasperi/SwiftHSVColorPicker#6]
This is probably a stupid question since I do not have any Swift experience so feel free to close this.
Is there a way to get live changes to hue and brightness by adding something to the ViewController without changing your code? 

It works by adding:

``` swift
self.socket.emit("ios", ["color": self.color.htmlRGBColor, "command": "static", "brightness": 1])
```

to the `brightnessSelected` and `hueAndSaturationSelected` function but I don't really like the idea of changing your core files.

**Comment by johankasperi** [comment]
I think you can add a GestureRecognizer to the ColorPicker in your root view and in that recognizer you can get the vars:
`self.colorPicker.brightness
self.colorPicker.hue
self.colorPicker.saturation`

But please note I haven't tried this myself. 

However are more general solution to this issue would be preferable, maybe with some sort of events or similar.

**Comment by johankasperi** [comment]
#7 Wrote a possible solution with delegates in this issue.
