### ISSUE TITLE
Detecting when finger is lifted of Color Wheel

### ISSUE THREAD

**Issue by shaqaruden** [johankasperi/SwiftHSVColorPicker#7]
I am using this Color Picker to set the Colors of my app. Currently, the app requires you to tap a button to set the current Color Picker color to its respective app color. Of course I would like to to be set when they lift off their finger. 

So I added a pan gesture to the color picker and the problem with this is while the gesture works fine it stops the color picker from changing color. Here is a video of me performing the gesture and as you can see when I am moving my mouse the console is updating with the changes. 
https://youtu.be/4Uk_KIwlWSo

**Comment by johankasperi** [comment]
Sorry for my late reply. I would solve your issue by instead of using a pan gesture, I would create a `SwiftHSVColorPickerDelegate` similar to the `ColorWheelDelegate` and `BrightnessViewDelegate`. I would then let the delegate of `SwiftHSVColorPicker` be the main ViewController. I think that would work but I haven't tried it and I currently don't have the time to do so. But something similar to this:

``` swift
protocol SwiftHSVColorPickerDelegate: class {
   func colorSelected(color: UIColor)
}

class SwiftHSVColorPicker:  UIView, ColorWheelDelegate, BrightnessViewDelegate  {
    weak var delegate: SwiftHSVColorPickerDelegate?
...
    func hueAndSaturationSelected(hue: CGFloat, saturation: CGFloat) {
        self.hue = hue
        self.saturation = saturation
        self.color = UIColor(hue: self.hue, saturation: self.saturation, brightness: self.brightness, alpha: 1.0)
        brightnessView.setViewColor(self.color)
        selectedColorView.setViewColor(self.color)
        delegate?.colorSelected(self.color)
    }

    func brightnessSelected(brightness: CGFloat) {
        self.brightness = brightness
        self.color = UIColor(hue: self.hue, saturation: self.saturation, brightness: self.brightness, alpha: 1.0)
        colorWheel.setViewBrightness(brightness)
        selectedColorView.setViewColor(self.color)
        delegate?.colorSelected(self.color)
    }
}
```

and then in the ViewController I would do:

``` swift
class ViewController: UIViewController, SwiftHSVColorPickerDelegate  {
    ....
    func colorSelected(color: UIColor) {
         print(color) // this should be printed everytime the gesture is performed
    }
}
```

Please let me know if this is working. If it is I might include it in the next release.

**Comment by johankasperi** [comment]
Forgot to say that you need to add: 

``` swift
colorPicker.delegate = self
```

in the viewDidLoad of your ViewController.

**Comment by shaqaruden** [comment]
I will give this a shot and reply back

**Comment by johankasperi** [comment]
No feedback on the suggestions. Closing this now.
