### ISSUE TITLE
Swift 3 

### ISSUE THREAD

**Issue by nirlachman-lp** [johankasperi/SwiftHSVColorPicker#8]
Hey,
Can you please add swift 3 compatibility? 

Thanks

**Comment by johankasperi** [comment]
Will try to do it in the next release. I currently don't have the time for it. 

If you want to make a pull request with the code updated to Swift 3 it would be great.

Thanks!

**Comment by johankasperi** [comment]
Fixed in pull #13 and added in version 1.1.1.
